/**
* Jenkins Doc: https://jenkins.io/doc/
*
**/

openshift.withCluster() {
  env.NAMESPACE = openshift.project()
  env.APP_NAME = "${JOB_NAME}".replaceAll(/-build.*/, '')
  echo "Starting Pipeline for ${APP_NAME}..."
}

pipeline {
    agent {
      label "maven"
    }
    stages {
        stage('Maven build') {
          steps {
            sh """
            mvn -v 
            cd CustomerOrderServicesProject
            mvn clean package
            """
          }
        }
        stage('Copy OCP deployment artifacts') {
          steps {
              // copy any raw yamls or json from openshift directory to be applied at deploy time
              sh """
              cd  Deployment/openshift/yaml
              mkdir -p ocp_deploy_assets
              cp  *.yaml ocp_deploy_assets || true
              """
              // print out the dir structure
              sh "find ocp_deploy_assets"
               }
            } 
            stage("Deploy objects") {
                  steps {
                    script {
                      openshift.withCluster() {
                        openshift.withProject() {
                          sh """
                          cd  Deployment/openshift/yaml
                          openshift.apply(ssc.yaml)
                          openshift.apply(dc.yaml)
                          openshift.apply(service.yaml)
                          openshift.apply(route.yaml)
                          """
                        }
                      }
                    }
                  }
                }  
              }
            }
