/**
* Jenkins Doc: https://jenkins.io/doc/
*
**/

openshift.withCluster() {
  env.NAMESPACE = openshift.project()
  env.APP_NAME = "${JOB_NAME}".replaceAll(/-build.*/, '')
  echo "Starting Pipeline for ${APP_NAME}..."
}

pipeline {
    agent {
      label "maven"
    }
    stages {
        stage('Maven build') {
          steps {
            sh """
            mvn -v 
            cd CustomerOrderServicesProject
            mvn clean package
            """
          }
        }
        stage("Deploy objects") {
                  steps {
                    script {
                      openshift.withCluster() {
                        openshift.withProject() {
                          sh """
                          cd  Deployment/openshift/yaml
                          openshift.apply(readFile(ssc.yaml))
                          openshift.apply(readFile(dc.yaml))
                          openshift.apply(readFile(service.yaml))
                          openshift.apply(readFile(route.yaml))
                          """
                        }
                      }
                    }
                  }
                }  
              }
            }
