image:
  repository: mycluster.icp:8500/default/twas # Specify your cluster CA domain here

ingress:
  enabled: true
  path: /demo/
  rewriteTarget: /CustomerOrderServicesWeb

configProperties:
  configMapName: my-custom-config-properties
